name: Deploy to Production Server Area
on:
  push:
    branches:
      - prod
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_PRODUCTION_SERVER }}
          username: ${{ secrets.FTP_PRODUCTION_USER }}
          password: ${{ secrets.FTP_PRODUCTION_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/public/**
